# netlify.toml – Configuration des headers de sécurité pour Keylity

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self';"

[[headers]]
  for = "/fonts.googleapis.com/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/fonts.gstatic.com/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
